version: '3'
 
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: sup3rs3cr3t
      MYSQL_DATABASE: poc-node-mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql-db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: mysql-phpmyadmin
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9001:80
volumes:
  mysql-db-data: